name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        REGISTRY: avzini
        IMAGE_NAME: web-app
        TAG: ${{ github.sha }}
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$IMAGE_NAME:$TAG .
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u $REGISTRY_USERNAME --password-stdin $REGISTRY
        docker push $REGISTRY/$IMAGE_NAME:$TAG
