name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        REGISTRY: avzini
        IMAGE_NAME: web-app
        TAG: ${{ github.sha }}    
      run: docker build . --file Dockerfile --tag $REGISTRY/$IMAGE_NAME:$TAG .
