name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: GoogleCloudPlatform/cloud-sdk-action@v3
      with:
        credentials: ${{ secrets.GKE_SA_KEY }}
        packages: kubectl

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project gamezone

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install webapp https://avnerzini.github.io/devops_assignment
