name: CI
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: start minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: true
          minikube-version: 1.31.2
          driver: none
          # container-runtime: containerd
          kubernetes-version: v1.27.4
        #   cpus: 4
        #   memory: 4000m
        #   cni: bridge
        #   addons: registry,ingress
        #   extra-config: 'kubelet.max-pods=10'
        #   feature-gates: 'DownwardAPIHugePages=true'
        #   mount-path: '/Users/user1/test-files:/testdata'
        #   wait: false
        #   insecure-registry: 'localhost:5000,10.0.0.0/24'
        #   start-args: '--delete-on-failure --subnet 192.168.50.0'
      # now you can run kubectl to see the pods in the cluster
      - name: kubectl
        run: |
          kubectl create namespace webapp
          helm repo add webapp https://avnerzini.github.io/devops_assignment
          helm install -n webapp webapp webapp/webapp
          sleep 15
          kubectl get all -n webapp
          minikube service list
          minikube service webapp -n webapp --url
          sleep 1000
          echo -n "------------------opening the service------------------"
          curl $(minikube service webapp -n webapp --url)/version